name: Linters and CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Requirements
        run: pip3 install -r requirements.txt

      - name: Linting with flake8
        run: flake8 jukebox.py

  CodeQL:
    runs-on: ubuntu-latest
    needs: [Linters]
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Requirements
        run: pip3 install -r requirements.txt

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          setup-python-dependencies: false
          queries: security-and-quality, security-extended
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
